openapi: 3.0.1
info:
  title: Data service integration
  description: API Definition of Data service integration
  version: 1.0.0
servers:
  - url: http://localhost:8290
paths:
  /services/Accounts:
    get:
      responses:
        '200':
          description: A user object.

              